#include "imports.fdeclare.h"
#ifndef bearssl_fdefine
#define bearssl_fdefine
#include "../src/aead/fdefine.ccm.c"
#include "../src/aead/fdefine.eax.c"
#include "../src/aead/fdefine.gcm.c"
#include "../src/codec/fdefine.ccopy.c"
#include "../src/codec/fdefine.dec16be.c"
#include "../src/codec/fdefine.dec16le.c"
#include "../src/codec/fdefine.dec32be.c"
#include "../src/codec/fdefine.dec32le.c"
#include "../src/codec/fdefine.dec64be.c"
#include "../src/codec/fdefine.dec64le.c"
#include "../src/codec/fdefine.enc16be.c"
#include "../src/codec/fdefine.enc16le.c"
#include "../src/codec/fdefine.enc32be.c"
#include "../src/codec/fdefine.enc32le.c"
#include "../src/codec/fdefine.enc64be.c"
#include "../src/codec/fdefine.enc64le.c"
#include "../src/codec/fdefine.pemdec.c"
#include "../src/codec/fdefine.pemenc.c"
#include "../src/ec/fdefine.ec_all_m15.c"
#include "../src/ec/fdefine.ec_all_m31.c"

#endif
